version: '3'
services:
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password --explicit-defaults-for-timestamp=1 --wait_timeout=300
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    volumes:
    - ./mysqldata:/var/lib/mysql
  php:
    image: karma8
    volumes:
      - ./:/app
    working_dir: /app
